export interface HubPreset {
  id: string;
  name: string;
  category: 'petroleum' | 'port' | 'factory' | 'warehouse' | 'agriculture' | 'transit';
  categoryLabel: string;
  address: string;
  state: string;
  lat: number;
  lng: number;
  geofenceRadius: number; // in meters
  tag: string;
}

export const NIGERIAN_HUB_PRESETS: HubPreset[] = [
  // 1. Petroleum & Gas Depots / Tank Farms
  {
    id: 'dangote-refinery',
    name: 'Dangote Petroleum Refinery & Petrochemical Complex',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Lekki Free Trade Zone, Ibeju-Lekki, Lagos',
    state: 'Lagos',
    lat: 6.4428,
    lng: 4.1082,
    geofenceRadius: 500,
    tag: 'Refinery / 650k BPD',
  },
  {
    id: 'atlas-cove',
    name: 'Atlas Cove Petroleum Jetty & Depot',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Takwa Bay Island, Lagos Harbour, Lagos',
    state: 'Lagos',
    lat: 6.4178,
    lng: 3.3986,
    geofenceRadius: 300,
    tag: 'NNPC Marine Depot',
  },
  {
    id: 'apapa-tank-farms',
    name: 'Apapa Tank Farms Cluster (Total, Oando, MRS)',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Dockyard Road / Ibafon Corridor, Apapa, Lagos',
    state: 'Lagos',
    lat: 6.4389,
    lng: 3.3592,
    geofenceRadius: 350,
    tag: 'Bulk Fuel Terminal',
  },
  {
    id: 'mosimi-depot',
    name: 'Mosimi Petroleum Loading Depot',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Ikorodu-Sagamu Expressway, Mosimi, Ogun',
    state: 'Ogun',
    lat: 6.7412,
    lng: 3.5518,
    geofenceRadius: 300,
    tag: 'Pipeline Depot',
  },
  {
    id: 'oghara-depot',
    name: 'Oghara Petroleum Depot (Prudent & Rainoil)',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Ethiope West Industrial Zone, Oghara, Delta',
    state: 'Delta',
    lat: 5.9387,
    lng: 5.6729,
    geofenceRadius: 300,
    tag: 'South-South Depot',
  },
  {
    id: 'warri-refinery',
    name: 'Warri Refining and Petrochemical Company (WRPC)',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Ekpan-Effurun Corridor, Warri, Delta',
    state: 'Delta',
    lat: 5.5682,
    lng: 5.7289,
    geofenceRadius: 400,
    tag: 'NNPC Refinery Depot',
  },
  {
    id: 'ph-refinery',
    name: 'Port Harcourt Refinery Jetty & Depot',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Alesa Eleme Expressway, Port Harcourt, Rivers',
    state: 'Rivers',
    lat: 4.7731,
    lng: 7.1084,
    geofenceRadius: 400,
    tag: 'Refinery Terminal',
  },
  {
    id: 'kaduna-refinery',
    name: 'Kaduna Refining and Petrochemical Depot (KRPC)',
    category: 'petroleum',
    categoryLabel: 'Petroleum & Gas Depot',
    address: 'Kachia Road, Chikun, Kaduna',
    state: 'Kaduna',
    lat: 10.4284,
    lng: 7.4129,
    geofenceRadius: 400,
    tag: 'Northern Central Depot',
  },

  // 2. Maritime Ports & Ocean Container Freight
  {
    id: 'apapa-port',
    name: 'Apapa Container Port (APM Terminals)',
    category: 'port',
    categoryLabel: 'Ocean Port & Container Freight',
    address: 'Wharf Road, Apapa Port Complex, Lagos',
    state: 'Lagos',
    lat: 6.4442,
    lng: 3.3644,
    geofenceRadius: 400,
    tag: 'Container Freight',
  },
  {
    id: 'tincan-port',
    name: 'Tin Can Island Port Complex (TICT & Port & Cargo)',
    category: 'port',
    categoryLabel: 'Ocean Port & Container Freight',
    address: 'Apapa-Oshodi Expressway, Tin Can Island, Lagos',
    state: 'Lagos',
    lat: 6.4381,
    lng: 3.3325,
    geofenceRadius: 400,
    tag: 'Ro-Ro & Bulk Cargo',
  },
  {
    id: 'onne-port',
    name: 'Onne Federal Ocean Terminal (FOT / FLT)',
    category: 'port',
    categoryLabel: 'Ocean Port & Container Freight',
    address: 'Onne Free Zone, Eleme LGA, Rivers',
    state: 'Rivers',
    lat: 4.7189,
    lng: 7.1512,
    geofenceRadius: 450,
    tag: 'Oil & Gas Free Zone',
  },
  {
    id: 'lekki-deep-sea',
    name: 'Lekki Deep Sea Port',
    category: 'port',
    categoryLabel: 'Ocean Port & Container Freight',
    address: 'Itoke Village, Ibeju-Lekki, Lagos',
    state: 'Lagos',
    lat: 6.4312,
    lng: 4.0519,
    geofenceRadius: 500,
    tag: 'Deep Sea Terminal',
  },
  {
    id: 'ptml-terminal',
    name: 'PTML Container & Vehicle Terminal',
    category: 'port',
    categoryLabel: 'Ocean Port & Container Freight',
    address: 'Mile 2 / Tin Can Link Road, Lagos',
    state: 'Lagos',
    lat: 6.4521,
    lng: 3.3289,
    geofenceRadius: 300,
    tag: 'Ro-Ro Terminal',
  },

  // 3. Heavy Industry & Cement Refineries
  {
    id: 'dangote-obajana',
    name: 'Dangote Cement Mega Plant (Obajana)',
    category: 'factory',
    categoryLabel: 'Heavy Manufacturing & Cement',
    address: 'Lokoja-Kabba Road, Obajana, Kogi',
    state: 'Kogi',
    lat: 7.9174,
    lng: 6.4318,
    geofenceRadius: 500,
    tag: 'Cement Mega Hub',
  },
  {
    id: 'dangote-ibese',
    name: 'Dangote Cement Works (Ibese)',
    category: 'factory',
    categoryLabel: 'Heavy Manufacturing & Cement',
    address: 'Ilaro-Ibese Road, Yewa North, Ogun',
    state: 'Ogun',
    lat: 7.0092,
    lng: 3.0421,
    geofenceRadius: 450,
    tag: 'Ogun Cement Plant',
  },
  {
    id: 'bua-okpella',
    name: 'BUA Cement Complex (Okpella)',
    category: 'factory',
    categoryLabel: 'Heavy Manufacturing & Cement',
    address: 'Benin-Abuja Highway, Okpella, Edo',
    state: 'Edo',
    lat: 7.2519,
    lng: 6.3491,
    geofenceRadius: 450,
    tag: 'BUA Edo Plant',
  },
  {
    id: 'bua-sokoto',
    name: 'BUA Cement Plant (Kalambaina)',
    category: 'factory',
    categoryLabel: 'Heavy Manufacturing & Cement',
    address: 'Kalambaina Industrial Area, Sokoto',
    state: 'Sokoto',
    lat: 13.0418,
    lng: 5.2109,
    geofenceRadius: 450,
    tag: 'Sokoto Cement',
  },
  {
    id: 'lafarge-ewekoro',
    name: 'Lafarge Africa Cement Plant (Ewekoro)',
    category: 'factory',
    categoryLabel: 'Heavy Manufacturing & Cement',
    address: 'Lagos-Abeokuta Expressway, Ewekoro, Ogun',
    state: 'Ogun',
    lat: 6.9328,
    lng: 3.2182,
    geofenceRadius: 400,
    tag: 'Lafarge Plant',
  },
  {
    id: 'nestle-agbara',
    name: 'Nestlé Nigeria Industrial Factory (Agbara)',
    category: 'factory',
    categoryLabel: 'Heavy Manufacturing & Cement',
    address: 'Agbara Industrial Estate, Ogun',
    state: 'Ogun',
    lat: 6.5182,
    lng: 3.1092,
    geofenceRadius: 300,
    tag: 'Food & Beverage',
  },

  // 4. FMCG & Interstate Commercial Depots
  {
    id: 'jumia-ikeja',
    name: 'Jumia Central Fulfilment Hub',
    category: 'warehouse',
    categoryLabel: 'FMCG & Logistics Center',
    address: 'Commercial Avenue, Ikeja Industrial Estate, Lagos',
    state: 'Lagos',
    lat: 6.5982,
    lng: 3.3421,
    geofenceRadius: 200,
    tag: 'E-commerce Hub',
  },
  {
    id: 'onitsha-central-hub',
    name: 'Onitsha Central Commercial Haulage Hub',
    category: 'warehouse',
    categoryLabel: 'FMCG & Logistics Center',
    address: 'Upper Iweka / Niger Bridge Corridor, Onitsha, Anambra',
    state: 'Anambra',
    lat: 6.1389,
    lng: 6.7821,
    geofenceRadius: 300,
    tag: 'Commercial Haulage',
  },
  {
    id: 'kano-bompai',
    name: 'Kano Bompai Industrial Logistics Depot',
    category: 'warehouse',
    categoryLabel: 'FMCG & Logistics Center',
    address: 'Bompai Industrial Area, Kano',
    state: 'Kano',
    lat: 12.0129,
    lng: 8.5419,
    geofenceRadius: 300,
    tag: 'Northern Hub',
  },
  {
    id: 'aba-ariaria',
    name: 'Ariaria International Logistics Depot',
    category: 'warehouse',
    categoryLabel: 'FMCG & Logistics Center',
    address: 'Faulks Road Corridor, Aba, Abia',
    state: 'Abia',
    lat: 5.1219,
    lng: 7.3512,
    geofenceRadius: 250,
    tag: 'Commercial Logistics',
  },

  // 5. Agricultural Silos & Grain Reserves
  {
    id: 'dawanau-grain',
    name: 'Dawanau International Grain Market',
    category: 'agriculture',
    categoryLabel: 'Agricultural Silo & Reserve',
    address: 'Dawanau, Dawakin Tofa LGA, Kano',
    state: 'Kano',
    lat: 12.0812,
    lng: 8.4419,
    geofenceRadius: 350,
    tag: 'West Africa Grain Hub',
  },
  {
    id: 'benue-agri-hub',
    name: 'Benue State Agricultural Logistics Depot',
    category: 'agriculture',
    categoryLabel: 'Agricultural Silo & Reserve',
    address: 'Makurdi-Gboko Road, Gboko, Benue',
    state: 'Benue',
    lat: 7.3218,
    lng: 8.9982,
    geofenceRadius: 300,
    tag: 'Food Basket Hub',
  },

  // 6. Interstate Passenger & Express Transit
  {
    id: 'oshodi-interchange',
    name: 'Oshodi Transport Interchange (Terminals 1, 2, 3)',
    category: 'transit',
    categoryLabel: 'Interstate Passenger Terminal',
    address: 'Agege Motor Road, Oshodi, Lagos',
    state: 'Lagos',
    lat: 6.5542,
    lng: 3.3519,
    geofenceRadius: 250,
    tag: 'Transit Mega Terminal',
  },
  {
    id: 'utako-terminal',
    name: 'Utako Central Passenger & Freight Depot',
    category: 'transit',
    categoryLabel: 'Interstate Passenger Terminal',
    address: 'Utako District, Abuja FCT',
    state: 'Abuja FCT',
    lat: 9.0682,
    lng: 7.4419,
    geofenceRadius: 250,
    tag: 'Abuja Central Terminal',
  },
];
