import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'pcm' | 'ig' | 'ha' | 'yo';

export interface LanguageOption {
  code: Language;
  name: string;
  flag: string;
  nativeName: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', flag: '🇬🇧', nativeName: 'English' },
  { code: 'pcm', name: 'Pidgin', flag: '🇳🇬', nativeName: 'Naija Pidgin' },
  { code: 'ig', name: 'Igbo', flag: '🇳🇬', nativeName: 'Asụsụ Igbo' },
  { code: 'ha', name: 'Hausa', flag: '🇳🇬', nativeName: 'Harshen Hausa' },
  { code: 'yo', name: 'Yoruba', flag: '🇳🇬', nativeName: 'Èdè Yorùbá' },
];

// Dictionary of translations for major app strings
export const translations: Record<Language, Record<string, string>> = {
  en: {
    howItWorks: 'How It Works?',
    trackWaybill: 'Track Waybill',
    enterTrackingNum: 'Enter Waybill Code (e.g. NNW-6530)',
    trackBtn: 'Track Now',
    portals: 'Select Your Portal',
    customerPortal: 'Customer Portal (Senders & Receivers)',
    staffPortal: 'Park Staff Login',
    managerPortal: 'Manager Login',
    companyPortal: 'Company Portal',
    adminPortal: 'Admin Portal',
    helpContact: 'Need Help? Contact Support',
    instantSearch: 'Instant Waybill Search',
    trackSub: 'Enter your Waybill Code (e.g. WB-890123 or NNW-6530) to track your package live',
    recentReceipts: 'Recent Receipts & Logs',
    builtForNigeria: 'Built for All Nigerian Motor Parks & Transport Companies',
    heroTitle: "Waybilla — Nigeria's #1 Dedicated Waybill Live Tracking & Fleet Platform",
    heroDesc: 'Waybilla tracks parcel waybills across Nigerian interstate transport companies and motor parks, and provides end-to-end Commercial Fleet Trip & Round-Trip Tracking with 3-checkpoint verification, per-trip & monthly billing, and driver portals.',
    liveStatusBadge: '⚡ Live Status Updates',
    digitalReceiptBadge: '📦 Digital Waybill Receipts',
    heavyFreightBadge: '🚛 Fleet Trip Tracking & Freight',
    quickNoticeTitle: '💡 Quick Notice for All Users:',
    whatIsWaybilla: 'What is Waybilla? Waybilla provides both digital motor park waybill tracking for parcel shipping and comprehensive Commercial Fleet Trip & Round-Trip Tracking for heavy transport trucks across Nigeria.',
    noForeignCodes: 'Please Note: No carry DHL, FedEx, or foreign tracking codes come here o! Only waybill codes created at participating Nigerian motor park or transport company counters work on Waybilla.',
    searchResult: 'Search Result',
    clearResult: 'Clear',
    loginSignUpCustomer: 'Log In / Sign Up to Customer Portal',
    customerSub: 'View receipts 🧾, 6-digit Pickup PIN 🔑 & history',
    howToLoginTitle: 'HOW TO LOG IN / REGISTER:',
    howToLoginDesc: 'Log in or sign up with the EXACT phone number given at the park as Sender or Receiver! All your waybills, receipts, and Pickup PINs will automatically appear.',
    parkStaffOperators: 'Park Staff / Operators:',
    gotItClose: 'Got It! Close Guide',
    howWorksSubtitle: 'Super simple guide for everyone!',
    forCustomersTitle: 'For Customers (Senders & Receivers):',
    custStep1: 'Give Your Phone Number at Park Counter: When dropping off or expecting a waybill, make sure staff types your phone number correctly.',
    custStep2: 'Log In with Your Phone Number: Sign up or log in on Waybilla using that exact same phone number to unlock your digital receipts 🧾 and live status!',
    custStep3: 'Track Live Vehicle Movement: Get real-time updates when the vehicle departs, travels interstate, and arrives at the park!',
    forStaffTitle: 'For Park Staff & Drivers:',
    staffStep1: 'Register Vehicle: First register the active loading vehicle/driver leaving your station.',
    staffStep2: 'Issue Waybill: Assign waybill to the vehicle and collect payment.',
    staffStep3: 'Depart & Arrive: Staff MUST click "Mark Vehicle as Departed" when leaving, and destination staff click "Mark Vehicle as Arrived" on arrival!',
    staffStep4: 'Receiver Phone Verification: Ask receiver for their phone number, verify on screen, and hand over waybill!',
    copyrightText: 'Waybilla Nigeria. Robust motor park tracking solutions.',
    signOut: 'Sign Out',
    activeShipments: 'Active Shipments',
    allShipments: 'All Shipments',
    pickupPin: 'Pickup PIN',
    status: 'Status',
    sender: 'Sender',
    receiver: 'Receiver',
    destination: 'Destination',
    origin: 'Origin',
    busNum: 'Bus / Vehicle Number',
    driver: 'Driver',
    date: 'Date',
    actions: 'Actions',
    downloadReceipt: 'Download Receipt',
    verifyCode: 'Verify Code',
    createWaybill: 'Issue / Register New Waybill',
    registerBus: 'Register Bus / Vehicle',
    outgoingBuses: 'Outgoing Vehicles',
    incomingBuses: 'Incoming Vehicles',
    waybillHistory: 'Waybill History',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    settings: 'Settings',
    myWaybillsReceipts: 'My Waybills & Receipts',
    activeWaybills: 'Active Waybills',
    deliveredWaybills: 'Delivered Waybills',
    totalSpent: 'Total Spent',
    searchPlaceholder: 'Search by Waybill code, item, or name...',
    noWaybillsFound: 'No waybills found for this search.',
    copyPin: 'Copy Pickup PIN',
    pinCopied: 'Pickup PIN Copied!',
    pickupInstruction: 'Show this 6-digit PIN to park staff when receiving your package at destination',
    customerDashboardTitle: 'Customer Portal',
    welcomeUser: 'Welcome back,',
    customerDesc: 'Track your personal waybills, digital receipts & 6-digit Pickup PINs',
    staffPortalTitle: 'Park Staff Portal',
    managerPortalTitle: 'Manager Station Portal',
    companyPortalTitle: 'Company Owner HQ Portal',
    adminPortalTitle: 'Super Admin Portal',
    overview: 'Overview',
    myBranches: 'Park Branches',
    staffMembers: 'Staff Members',
    vehiclesAndBuses: 'Vehicles & Buses',
    revenueLogs: 'Revenue Logs',
    systemStats: 'System Statistics',
    markDeparted: 'Mark Vehicle as Departed',
    markArrived: 'Mark Vehicle as Arrived',
    senderInfo: '1. Sender Information',
    senderNameLabel: 'Sender Full Name',
    senderPhoneLabel: 'Sender Phone Number',
    receiverInfo: '2. Receiver Information',
    receiverNameLabel: 'Receiver Full Name',
    receiverPhoneLabel: 'Receiver Phone Number',
    packageInfo: '3. Package & Payment Details',
    itemDescLabel: 'Package Item Description & Weight',
    waybillFeeLabel: 'Waybill Fee / Charge (₦)',
    destinationParkLabel: '4. Destination Motor Park Station',
    selectParkOption: '-- Select Destination Motor Park --',
    selectBusLabel: '5. Select Loading Bus / Vehicle',
    selectBusOption: '-- Select Active Loading Vehicle --',
    noBusesWarning: 'No active loading vehicle found for this route. Please register a bus first!',
    submitWaybill: 'Issue & Save Waybill',
    plateNumber: 'Vehicle Plate Number',
    driverName: 'Driver Name',
    driverPhone: 'Driver Phone Number',
    totalRevenue: 'Total Revenue',
    todayWaybills: 'Today Waybills',
    activeBusesCount: 'Active Loading Buses',
    details: 'Details',
    shareWhatsApp: 'Share via WhatsApp',
  },
  pcm: {
    howItWorks: 'How E Dey Work?',
    trackWaybill: 'Trace Your Waybill',
    enterTrackingNum: 'Put Waybill Code (e.g. NNW-6530)',
    trackBtn: 'Trace Am Now',
    portals: 'Select Which Portal You Wan Enter',
    customerPortal: 'Customer Portal (Senders & Receivers)',
    staffPortal: 'Park Staff Login',
    managerPortal: 'Manager Login',
    companyPortal: 'Transport Company Portal',
    adminPortal: 'Admin Portal',
    helpContact: 'You Need Help? Call Support',
    instantSearch: 'Quick Waybill Search',
    trackSub: 'Put your Waybill Code (e.g. WB-890123 or NNW-6530) to trace your package live',
    recentReceipts: 'Recent Receipts & Logs',
    builtForNigeria: 'Built for All Nigerian Motor Parks & Transport Companies',
    heroTitle: "Waybilla — Nigeria Number 1 Live Waybill Tracking & Fleet Platform",
    heroDesc: 'Waybilla dey trace waybill for Nigerian motor parks, and also provide full Commercial Fleet Trip & Round-Trip Tracking for heavy trucks with 3-checkpoint verification and driver portals.',
    liveStatusBadge: '⚡ Live Status Updates',
    digitalReceiptBadge: '📦 Digital Receipts',
    heavyFreightBadge: '🚛 Fleet Trip Tracking & Heavy Goods',
    quickNoticeTitle: '💡 Quick Notice For Everybody:',
    whatIsWaybilla: 'Wetin be Waybilla? Waybilla dey trace motor park waybills for parcel shipping and also manage Commercial Fleet Trip & Round-Trip Tracking for heavy transport trucks across Nigeria.',
    noForeignCodes: 'Abeg Note: No carry DHL or FedEx code come here o! Only waybill codes created for Nigerian motor parks dey work here.',
    searchResult: 'Search Result',
    clearResult: 'Clear Am',
    loginSignUpCustomer: 'Log In / Sign Up to Customer Portal',
    customerSub: 'See receipts 🧾, 6-digit Pickup PIN 🔑 & history',
    howToLoginTitle: 'HOW TO LOG IN / REGISTER:',
    howToLoginDesc: 'Log in with the EXACT phone number dem write for your waybill receipt as Sender or Receiver! All your waybills and Pickup PINs go show automatically.',
    parkStaffOperators: 'Park Staff / Operators:',
    gotItClose: 'I Don Hear! Close Guide',
    howWorksSubtitle: 'Simple guide for everybody!',
    forCustomersTitle: 'For Customers (People Wey Dey Send & Receive):',
    custStep1: 'Give Your Phone Number For Park: Make sure staff type your correct phone number when dem dey create waybill.',
    custStep2: 'Log In With Phone Number: Put that exact phone number on Waybilla to see your receipt 🧾 and tracking status!',
    custStep3: 'Follow Motor Movement: See live when motor leave park, travel road, and arrive destination park!',
    forStaffTitle: 'For Park Staff & Drivers:',
    staffStep1: 'Register Motor: First register the motor or driver wey dey load go another park.',
    staffStep2: 'Create Waybill: Add waybill to the motor and collect money.',
    staffStep3: 'Depart & Arrive: Click "Mark Vehicle as Departed" when motor leave, and destination staff click "Mark Vehicle as Arrived" when motor land!',
    staffStep4: 'Verify Receiver Phone: Ask receiver for phone number, verify am on screen, then give am him package!',
    copyrightText: 'Waybilla Nigeria. Reliable motor park tracking platform.',
    signOut: 'Sign Out',
    activeShipments: 'Active Packages',
    allShipments: 'All Packages',
    pickupPin: 'Pickup PIN',
    status: 'Status',
    sender: 'Person Wey Send',
    receiver: 'Person Wey Receive',
    destination: 'Where E Dey Go',
    origin: 'Where E From Start',
    busNum: 'Motor Number',
    driver: 'Driver',
    date: 'Date',
    actions: 'Wetin To Do',
    downloadReceipt: 'Download Receipt',
    verifyCode: 'Verify Code',
    createWaybill: 'Create / Issue Waybill',
    registerBus: 'Register Motor / Bus',
    outgoingBuses: 'Motors Wey Dey Go',
    incomingBuses: 'Motors Wey Dey Come',
    waybillHistory: 'Waybill History',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    settings: 'Settings',
    myWaybillsReceipts: 'My Waybills & Receipts',
    activeWaybills: 'Waybills Wey Dey Road',
    deliveredWaybills: 'Waybills Wey Don Land',
    totalSpent: 'Total Money Spent',
    searchPlaceholder: 'Search with Waybill code, item, or name...',
    noWaybillsFound: 'No waybill found for this search.',
    copyPin: 'Copy Pickup PIN',
    pinCopied: 'Pickup PIN Don Copy!',
    pickupInstruction: 'Show this 6-digit PIN to park staff when you wan collect your package for destination',
    customerDashboardTitle: 'Customer Portal',
    welcomeUser: 'Welcome back,',
    customerDesc: 'Trace your waybills, digital receipts & 6-digit Pickup PINs',
    staffPortalTitle: 'Park Staff Portal',
    managerPortalTitle: 'Manager Station Portal',
    companyPortalTitle: 'Company Owner HQ Portal',
    adminPortalTitle: 'Super Admin Portal',
    overview: 'Overview',
    myBranches: 'Park Branches',
    staffMembers: 'Staff Members',
    vehiclesAndBuses: 'Motors & Buses',
    revenueLogs: 'Revenue Logs',
    systemStats: 'System Statistics',
    markDeparted: 'Mark Motor as Departed',
    markArrived: 'Mark Motor as Arrived',
    senderInfo: '1. Person Wey Dey Send Package',
    senderNameLabel: 'Full Name of Person Wey Dey Send',
    senderPhoneLabel: 'Phone Number of Person Wey Dey Send',
    receiverInfo: '2. Person Wey Wan Receive Package',
    receiverNameLabel: 'Full Name of Person Wey Wan Receive',
    receiverPhoneLabel: 'Phone Number of Person Wey Wan Receive',
    packageInfo: '3. Package & Money Details',
    itemDescLabel: 'Wetin Dey Inside Package',
    waybillFeeLabel: 'Waybill Price / Charge (₦)',
    destinationParkLabel: '4. Park Where Motor Dey Go',
    selectParkOption: '-- Select Destination Park --',
    selectBusLabel: '5. Select Motor Wey Dey Load',
    selectBusOption: '-- Select Motor Wey Dey Load --',
    noBusesWarning: 'No motor dey load for this route right now. Register motor first!',
    submitWaybill: 'Issue & Save Waybill',
    plateNumber: 'Motor Plate Number',
    driverName: 'Driver Name',
    driverPhone: 'Driver Phone Number',
    totalRevenue: 'Total Money Collected',
    todayWaybills: 'Today Waybills',
    activeBusesCount: 'Motors Wey Dey Load',
    details: 'Details',
    shareWhatsApp: 'Share for WhatsApp',
  },
  ig: {
    howItWorks: 'Kedu Ka Ọ Dị Aṅaa?',
    trackWaybill: 'Chọọ Waybill Gị',
    enterTrackingNum: 'Tinye Koodu Waybill (dịka NNW-6530)',
    trackBtn: 'Chọọ Ya Ugbu A',
    portals: 'Pịa Ebe Ị Chọrọ Isonye',
    customerPortal: 'Pọtụ Nke Ndị Ahịa (Ndị Thọrọ & Ndị Na-anata)',
    staffPortal: 'Pọtụ Nke Ndị Ọrụ Park',
    managerPortal: 'Pọtụ Nke Mmanịja',
    companyPortal: 'Pọtụ Nke Ụlọ Ọrụ Transport',
    adminPortal: 'Pọtụ Nke Admin',
    helpContact: 'Ị Chọrọ Enyemaka? Kpọọ Ndị Support',
    instantSearch: 'Mmanụ Ahụ Ike Waybill',
    trackSub: 'Tinye koodu Waybill gị (dịka WB-890123 ma ọ bụ NNW-6530) iji chọpụta ebe package gị dị',
    recentReceipts: 'Akwụkwọ Azụmahịa So Ha',
    builtForNigeria: 'Emere Maka Park Niile Dị na Naịjirịa',
    heroTitle: "Waybilla — Ebe Izizi Na Naịjirịa Maka Inyocha Waybill Live",
    heroDesc: 'Waybilla na-enyocha waybill gị na park ụgbọ ala niile na Naịjirịa — gụnyere park ama ama dịka Nwanyi Imo Park Nnewi (ebe a na-ebuba traktọ na gwongwo na-aga Kano, Lagos, Abuja, Onitsha).',
    liveStatusBadge: '⚡ Mmelite Okwu Ebe Ụgbọ Ala Dị',
    digitalReceiptBadge: '📦 Rịsịtị Waybill E Nwere na Ekwe Ntị',
    heavyFreightBadge: '🚛 Ụgbọ Ala, Traktọ & Gwongwo Ukwu',
    quickNoticeTitle: '💡 Ozi Dị Nkpa Maka Onye Niile:',
    whatIsWaybilla: 'Gịnị bụ Waybilla? Waybilla bụ sistemụ na-enyocha waybill e debanyere na park ụgbọ ala na ụlọ ọrụ transport na Naịjirịa.',
    noForeignCodes: 'Biko Mara: Koodu DHL ma ọ bụ FedEx anaghị arụ ọrụ ebe a o! Sọọsọ koodu waybill e kere na park ụgbọ ala na-arụ ọrụ.',
    searchResult: 'Ihe Arụpụtara',
    clearResult: 'Kpochapụ',
    loginSignUpCustomer: 'Banye Na Pọtụ Ndị Ahịa',
    customerSub: 'Hụ rịsịtị gị 🧾, Pickup PIN 🔑 na akụkọ mba gị',
    howToLoginTitle: 'KA E SI EBANYE / KA E SI EDEBANYE INAME:',
    howToLoginDesc: 'Banye na nọmba ekwe ntị ahụ ị nyere na park dịka Onye Ịte ihe ma ọ bụ Onye Na-anata! Waybill na rịsịtị gị niile ga-apụta ozugbo.',
    parkStaffOperators: 'Ndị Ọrụ Park & Ndị Onye Mmanịja:',
    gotItClose: 'Atọrọ m gị! Mechie Ntuziaka',
    howWorksSubtitle: 'Akwụkwọ ntuziaka dị mfe maka onye niile!',
    forCustomersTitle: 'Maka Ndị Ahịa (Ndị Zuru & Ndị Na-anata):',
    custStep1: 'Nyepụ Nọmba Ekwe Ntị Gị Na Park: Hụ na ndị ọrụ park dere nọmba gị nke ọma.',
    custStep2: 'Banye Na Nọmba Ekwe Ntị Gị: Banye na Waybilla iji hụ rịsịtị gị na ebe gwongwo gị ruru!',
    custStep3: 'Soro Ụgbọ Ala Mgbe Ọ Na-aga: Nweta ozi mgbe ụgbọ ala hapụrụ park na mgbe ọ rutere destination!',
    forStaffTitle: 'Maka Ndị Ọrụ Park & Ndị Onye Ịkwọ Ụgbọ Ala:',
    staffStep1: 'Debanye Ụgbọ Ala: Nke mbụ, debanye ụgbọ ala na-eju gaa park ọzọ.',
    staffStep2: 'Meo Waybill: Tinye waybill na ụgbọ ala ahụ nakwa nara ego.',
    staffStep3: 'Pụọ Na Rute: Ndị ọrụ ga-pịa "Mark Vehicle as Departed", ndị park ọzọ ga-pịa "Mark Vehicle as Arrived" mgbe ọ rutere!',
    staffStep4: 'Hụ Nọmba Onye Na-anata: Jụọ onye na-anata nọmba ya na screen tupu ị nyefee ya gwongwo ya!',
    copyrightText: 'Waybilla Nigeria. Sistemụ nyocha park ụgbọ ala na-arụ ọrụ nke ọma.',
    signOut: 'Pụọ Mba',
    activeShipments: 'Gwongwo Na-aga Mba',
    allShipments: 'Gwongwo Niile',
    pickupPin: 'Pickup PIN',
    status: 'Ebe Ọ Dị',
    sender: 'Onye Zipụrụ',
    receiver: 'Onye Na-anata',
    destination: 'Ebe Ọ Na-aga',
    origin: 'Ebe Ọ Si Pụta',
    busNum: 'Nọmba Ụgbọ Ala',
    driver: 'Onye Ịkwọ Ụgbọ Ala',
    date: 'Ụbọchị',
    actions: 'Ihe Ị Ga-eme',
    downloadReceipt: 'Budata Rịsịtị',
    verifyCode: 'Lere Koodu',
    createWaybill: 'Meo Waybill Ọhụrụ',
    registerBus: 'Debanye Ụgbọ Ala',
    outgoingBuses: 'Ụgbọ Ala Na-apụ Apụ',
    incomingBuses: 'Ụgbọ Ala Na-abata Abata',
    waybillHistory: 'Akụkọ Waybill Niile',
    dashboard: 'Ddashbọọdụ',
    analytics: 'Nyocha Ego',
    settings: 'Ntọala',
    myWaybillsReceipts: 'Waybill M & Akwụkwọ Ego',
    activeWaybills: 'Waybill Na-aga Mba',
    deliveredWaybills: 'Waybill E Ruteworo',
    totalSpent: 'Ego Niile E Tiri',
    searchPlaceholder: 'Chọọ koodu waybill, ihe, ma ọ bụ aha...',
    noWaybillsFound: 'Enweghị waybill e nwetara maka search a.',
    copyPin: 'Kopịrị Pickup PIN',
    pinCopied: 'A Kopịrị Pickup PIN!',
    pickupInstruction: 'Gosi koodu PIN 6 a ndị ọrụ park mgbe ị na-anata gwongwo gị na park destination',
    customerDashboardTitle: 'Pọtụ Ndị Ahịa',
    welcomeUser: 'Nnọọ mgbe ọzọ,',
    customerDesc: 'Nyochaa waybill gị, rịsịtị gị na koodu Pickup PIN gị',
    staffPortalTitle: 'Pọtụ Ndị Ọrụ Park',
    managerPortalTitle: 'Pọtụ Mmanịja Park',
    companyPortalTitle: 'Pọtụ Ụlọ Ọrụ Transport',
    adminPortalTitle: 'Pọtụ Super Admin',
    overview: 'Nchikota',
    myBranches: 'Park Ụgbọ Ala Niile',
    staffMembers: 'Ndị Ọrụ Niile',
    vehiclesAndBuses: 'Ụgbọ Ala Niile',
    revenueLogs: 'Akụkọ Ego E Nwetara',
    systemStats: 'Nduzi Sistemụ',
    markDeparted: 'Kaa Ụgbọ Ala Dịka Nke Pụrụ Apụ',
    markArrived: 'Kaa Ụgbọ Ala Dịka Nke Rutere Arute',
    senderInfo: '1. Ozi Onye Na-eziga Gwongwo',
    senderNameLabel: 'Aha Onye Na-eziga',
    senderPhoneLabel: 'Lamba Ekwe Ntị Onye Na-eziga',
    receiverInfo: '2. Ozi Onye Na-anata Gwongwo',
    receiverNameLabel: 'Aha Onye Na-anata',
    receiverPhoneLabel: 'Lamba Ekwe Ntị Onye Na-anata',
    packageInfo: '3. Nkọwa Gwongwo & Ego Waybill',
    itemDescLabel: 'Nkọwa Gwongwo Nọ N\'ime Package',
    waybillFeeLabel: 'Ego Waybill (₦)',
    destinationParkLabel: '4. Park Destination Ebe Ọ Na-aga',
    selectParkOption: '-- Rọrọ Park Destination --',
    selectBusLabel: '5. Rọrọ Ụgbọ Ala Na-eloadu',
    selectBusOption: '-- Rọrọ Ụgbọ Ala Na-eloadu --',
    noBusesWarning: 'Enweghị ụgbọ ala na-eloadu maka ala a. Biko debanye ụgbọ ala tupu ị meo waybill!',
    submitWaybill: 'Meo Waybill & Chekwaa Ya',
    plateNumber: 'Lamba Plate Ụgbọ Ala',
    driverName: 'Aha Dịreba',
    driverPhone: 'Lamba Dịreba',
    totalRevenue: 'Ego Niile E Nwetara',
    todayWaybills: 'Waybill Nke Taa',
    activeBusesCount: 'Ụgbọ Ala Na-eloadu',
    details: 'Nchịkọta',
    shareWhatsApp: 'Ziga na WhatsApp',
  },
  ha: {
    howItWorks: 'Yaya Yake Aiki?',
    trackWaybill: 'Nemi Waybill Dinka',
    enterTrackingNum: 'Saka Lambar Waybill (misali NNW-6530)',
    trackBtn: 'Bincika Yanzu',
    portals: 'Zaɓi Wajen Shiga',
    customerPortal: 'Wajen Abokan Ciniki',
    staffPortal: 'Wajen Ma\'aikata',
    managerPortal: 'Wajen Manaja',
    companyPortal: 'Wajen Kamfani',
    adminPortal: 'Wajen Admin',
    helpContact: 'Kuna Buƙatar Ƙarin Taimako?',
    instantSearch: 'Binciken Waybill Da Sauri',
    trackSub: 'Saka lambar Waybill dinka (misali WB-890123 ko NNW-6530) domin gano inda kayanka yake',
    recentReceipts: 'Rasitocina Na Kwanan Nan',
    builtForNigeria: 'An Kera Domin Dukkan Tashoshin Motocin Najeriya',
    heroTitle: "Waybilla — Dandamali Na Ɗaya A Najeriya Domin Binciken Waybill Katse-Katse",
    heroDesc: 'Waybilla yana binciken waybill a duk tashoshin motoci da kamfanonin sufuri a Najeriya — har da tashoshi kamar Nwanyi Imo Park Nnewi.',
    liveStatusBadge: '⚡ Sabunta Halin Mota Kafin Bincike',
    digitalReceiptBadge: '📦 Rasitin Waybill Na Yanar Gizo',
    heavyFreightBadge: '🚛 Motoci, Garuruwa & Kaya Mai Nauyi',
    quickNoticeTitle: '💡 Sanarwa Mai Muhimmanci Domin Kowa:',
    whatIsWaybilla: 'Mene ne Waybilla? Waybilla tsari ne na binciken kaya da aka yi rajista a tashoshin motoci a Najeriya.',
    noForeignCodes: 'Lura: Lambobin DHL ko FedEx ba sa aiki a nan! Kawai lambobin waybill na tashoshin Najeriya ke aiki.',
    searchResult: 'Sakamakon Bincike',
    clearResult: 'Goge',
    loginSignUpCustomer: 'Shiga Wajen Abokan Ciniki',
    customerSub: 'Duba rasitocin ku 🧾, Pickup PIN 🔑 da tarihin kaya',
    howToLoginTitle: 'YADDA ZAKU SHIGA KO YI RAJISTA:',
    howToLoginDesc: 'Yi amfani da ainihin lambar wayar da kuka bayar a tashar mota azaman Mai Aikawa ko Mai Karɓa!',
    parkStaffOperators: 'Ma\'aikatan Tasha / Masu Tuƙi:',
    gotItClose: 'Na Fahimta! Rufe',
    howWorksSubtitle: 'Jagora mai sauƙi domin kowa!',
    forCustomersTitle: 'Domin Abokan Ciniki (Masu Aikawa & Karɓa):',
    custStep1: 'Bada Lambar Wayarku A Tasha: Tabbatar ma\'aikaci ya rubuta lambar wayarku daidai.',
    custStep2: 'Shiga Da Lambar Waya: Yi amfani da wannan lambar a Waybilla don ganin rasitinku 🧾 da inda kayanku yake!',
    custStep3: 'Bi Motsin Mota: Kalli lokacin da mota ta tashi kuma ta ƙaraso tashar garinku!',
    forStaffTitle: 'Domin Ma\'aikata & Masu Tuƙi:',
    staffStep1: 'Yi Rajistar Mota: Farko yi rajistar motar da ke ɗaukar kaya.',
    staffStep2: 'Ƙirƙiri Waybill: Haɗa waybill da motar kuma karɓi kuɗi.',
    staffStep3: 'Tashi & Sauka: Latsa "Mark Vehicle as Departed" sa\'ad da mota ta tashi, kuma a latsa "Arrived" lokacin da ta ƙaraso!',
    staffStep4: 'Tabbatar Da Lambar Mai Karɓa: Tambayi mai karɓa lambar wayarsa a allon kwamfuta kafin ba shi kaya!',
    copyrightText: 'Waybilla Nigeria. Tsarin binciken tashoshin mota amintacce.',
    signOut: 'Fita',
    activeShipments: 'Kaya Masu Motsi',
    allShipments: 'Dukkan Kaya',
    pickupPin: 'Lambar Karɓa (PIN)',
    status: 'Hali',
    sender: 'Mai Aikawa',
    receiver: 'Mai Karɓa',
    destination: 'Ina Yake Tafiya',
    origin: 'Inda Ake Fitowa',
    busNum: 'Lambar Mota',
    driver: 'Mai Tuƙi',
    date: 'Kwanan Wata',
    actions: 'Ayyuka',
    downloadReceipt: 'Sauke Rasiti',
    verifyCode: 'Tabbatar Da Lamba',
    createWaybill: 'Ƙirƙiri Sabon Waybill',
    registerBus: 'Yi Rajistar Mota',
    outgoingBuses: 'Motocin Da Ke Tashi',
    incomingBuses: 'Motocin Da Ke Ƙarasowa',
    waybillHistory: 'Tarihin Waybill',
    dashboard: 'Dandamaloli',
    analytics: 'Binciken Kuɗi',
    settings: 'Saituna',
    myWaybillsReceipts: 'Rasitoci Na Da Waybill',
    activeWaybills: 'Waybills Masu Motsi',
    deliveredWaybills: 'Waybills Da Suka Ƙaraso',
    totalSpent: 'Jimillar Kuɗin Da Aka Kashe',
    searchPlaceholder: 'Bincika ta lambar waybill, kaya, ko suna...',
    noWaybillsFound: 'Babu waybill da aka samu.',
    copyPin: 'Kafi Lambar PIN',
    pinCopied: 'An Kafi Lambar PIN!',
    pickupInstruction: 'Nuna wannan PIN guda 6 ga ma\'aikatan tasha lokacin karɓar kayanku',
    customerDashboardTitle: 'Wajen Abokan Ciniki',
    welcomeUser: 'Sannu da dawowa,',
    customerDesc: 'Bincika waybill, rasitocin yanar gizo da lambobin PIN',
    staffPortalTitle: 'Wajen Ma\'aikata',
    managerPortalTitle: 'Wajen Manaja',
    companyPortalTitle: 'Wajen Gudanar Da Kamfani',
    adminPortalTitle: 'Wajen Babban Admin',
    overview: 'Tawatsawa',
    myBranches: 'Tashoshin Mota',
    staffMembers: 'Ma\'aikata',
    vehiclesAndBuses: 'Motoci',
    revenueLogs: 'Rahoton Kuɗi',
    systemStats: 'Ƙididdigar Tsari',
    markDeparted: 'Alanta Mota A Matsayin Ta Tashi',
    markArrived: 'Alanta Mota A Matsayin Ta Ƙaraso',
    senderInfo: '1. Bayanin Mai Aikawa',
    senderNameLabel: 'Cikakken Sunan Mai Aikawa',
    senderPhoneLabel: 'Lambar Wayar Mai Aikawa',
    receiverInfo: '2. Bayanin Mai Karɓa',
    receiverNameLabel: 'Cikakken Sunan Mai Karɓa',
    receiverPhoneLabel: 'Lambar Wayar Mai Karɓa',
    packageInfo: '3. Bayanin Kaya & Kuɗi',
    itemDescLabel: 'Bayanin Kaya Da Nauyinsa',
    waybillFeeLabel: 'Kuɗin Waybill (₦)',
    destinationParkLabel: '4. Tashar Mota Da Za A Je',
    selectParkOption: '-- Zaɓi Tashar Mota --',
    selectBusLabel: '5. Zaɓi Motar Da Ke Ɗaukar Kaya',
    selectBusOption: '-- Zaɓi Mota --',
    noBusesWarning: 'Babu mota mai tashi a yanzu. Yi rajistar mota tukuna!',
    submitWaybill: 'Buga & Ajiye Waybill',
    plateNumber: 'Lambar Mota',
    driverName: 'Sunan Direba',
    driverPhone: 'Lambar Direba',
    totalRevenue: 'Jimillar Kuɗin Da Aka Samari',
    todayWaybills: 'Waybills Na Yau',
    activeBusesCount: 'Motoci Masu Ɗaukar Kaya',
    details: 'Cikakken Bayani',
    shareWhatsApp: 'Aika ta WhatsApp',
  },
  yo: {
    howItWorks: 'Báwo Ni Ó Ṣe Ń Ṣiṣẹ́?',
    trackWaybill: 'Tọpa Ẹrù Rẹ',
    enterTrackingNum: 'Tẹ Koodu Waybill (bíi NNW-6530)',
    trackBtn: 'Tọpa Agbára Rẹ Níṣinsìnyí',
    portals: 'Yan Báyìí Lóti Wọlé',
    customerPortal: 'Ibì Ndí Oníbàárà',
    staffPortal: 'Ibì Ndí Oníṣẹ́ Park',
    managerPortal: 'Ibì Ndí Mánéjà',
    companyPortal: 'Ibì Ndí Kháńpánì',
    adminPortal: 'Ibì Ndí Admin',
    helpContact: 'Ṣé O Ní Bùkátà Tí Tí Tí?',
    instantSearch: 'Àwárí Ẹrù Pátápátá',
    trackSub: 'Tẹ koodu Waybill rẹ (bíi WB-890123 tàbí NNW-6530) láti tọpa ẹrù rẹ gangan',
    recentReceipts: 'Àwọn Risiti Tuntun',
    builtForNigeria: 'A Kọ Ó Fún Gbogbo Garaji Ọkọ̀ Ní Nàìjíríà',
    heroTitle: "Waybilla — Ètò Tọ́tọ̀ Tí Ó Dára Jù Lọ Látì Tọpa Ẹrù Ní Nàìjíríà",
    heroDesc: 'Waybilla ń tọpa ẹrù kọjá gbogbo àwọn garaji ọkọ̀ àti ilé-ṣẹ́ transport ní Nàìjíríà — pẹ̀lú àwọn garaji ńlá bíi Nwanyi Imo Park Nnewi.',
    liveStatusBadge: '⚡ Mímọ̀ Nípa Níbo Ni Ọkọ̀ Wà',
    digitalReceiptBadge: '📦 Risiti Ẹrù Lori Fóònù Rẹ',
    heavyFreightBadge: '🚛 Ọkọ̀ Ńlá, Ọkọ̀ Ẹrù Àti Ẹrù Ńlá',
    quickNoticeTitle: '💡 Àkíyèsí Pataki Fún Gbogbo Eniyan:',
    whatIsWaybilla: 'Kí ni Waybilla? Waybilla jẹ́ ètò tí ó ń tọpa ẹrù tí a fi orukọ rẹ̀ sílẹ̀ ní àwọn garaji ọkọ̀ ní Nàìjíríà.',
    noForeignCodes: 'Àkíyèsí: Koodu DHL tabi FedEx kò ṣiṣẹ́ níhìn-ín o! Àwọn koodu ẹrù garaji Nàìjíríà nìkan ni ó ń ṣiṣẹ́.',
    searchResult: 'Agbára Àwárí',
    clearResult: 'Nù Kúrò',
    loginSignUpCustomer: 'Wọlé Sí Ibì Oníbàárà',
    customerSub: 'Wo risiti rẹ 🧾, Pickup PIN 🔑 ati itan ẹrù rẹ',
    howToLoginTitle: 'BÁWO NI ṢE WỌLÉ TÀBÍ BẸ̀RẸ̀:',
    howToLoginDesc: 'Wọlé pẹ̀lú nọ́ńbà fóònù gangan tí o fun wọn ní garaji gẹ́gẹ́ bí Onítẹ́rù tàbí Onígbàgbọ́!',
    parkStaffOperators: 'Àwọn Oníṣẹ́ Garaji & Dokita Ọkọ̀:',
    gotItClose: 'Mo Ti Mọ̀! Ti Bọtini Wa',
    howWorksSubtitle: 'Agbára itọsọna ti o rọrun fún gbogbo eniyan!',
    forCustomersTitle: 'Fún Àwọn Oníbàárà (Onítẹ́rù & Onígbàgbọ́):',
    custStep1: 'Fun Won Ni Nọ́ńbà Fóònù Rẹ Ní Garaji: Rí i daju pé àwọn oníṣẹ́ kọ nọ́ńbà fóònù rẹ dáradára.',
    custStep2: 'Wọlé Pẹ̀lú Nọ́ńbà Fóònù Rẹ: Wọlé sí Waybilla láti rí risiti rẹ 🧾 àti níbo ni ẹrù rẹ wa!',
    custStep3: 'Tọpa Ọkọ̀ Bi Ó Ṣe Ń Lọ: Mọ àkókò tí ọkọ̀ kúrò ní garaji àti gbàgbọ́ pé ó ti dé garaji rẹ!',
    forStaffTitle: 'Fún Àwọn Oníṣẹ́ Garaji & Àwọn Wọ̀bọ̀:',
    staffStep1: 'Bẹ̀rẹ̀ Ọkọ̀: Bẹ̀rẹ̀ nípase fifi orukọ ọkọ̀ tí ó ń lọ sí garaji miiran sílẹ̀.',
    staffStep2: 'Kọ Risiti Ẹrù: Fi ẹrù pọ mọ ọkọ̀ náà kí o sì gbà owó.',
    staffStep3: 'Kúrò & Dé: Tẹ "Mark Vehicle as Departed" nígbà tí ọkọ̀ kúrò, kí àwọn oníṣẹ́ garaji miiran tẹ "Arrived" nígbà tí ó dé!',
    staffStep4: 'Fìdí Nọ́ńbà Onígbàgbọ́ Múlẹ̀: Bere fún nọ́ńbà fóònù onígbàgbọ́ lori screen kí o to fun ni ẹrù rẹ̀!',
    copyrightText: 'Waybilla Nigeria. Ètò tọpa garaji ọkọ̀ tí ó dára púpọ̀.',
    signOut: 'Jáde Wọlé',
    activeShipments: 'Àwọn Ẹrù Tí Ń Lọ',
    allShipments: 'Gbogbo Àwọn Ẹrù',
    pickupPin: 'Pickup PIN',
    status: 'Báwo Ni Ó Ṣe Wà',
    sender: 'Onítẹ́rù',
    receiver: 'Onígbàgbọ́',
    destination: 'Níbo Ni Ó Ṣe Ń Lọ',
    origin: 'Níbo Ni Ó Ti Bẹ̀rẹ̀',
    busNum: 'Nọ́ńbà Ọkọ̀',
    driver: 'Mọ́tò Dokita',
    date: 'Ọjọ́',
    actions: 'Àwọn Ìgbésẹ̀',
    downloadReceipt: 'Download Risiti',
    verifyCode: 'Fìdí Koodu Múlẹ̀',
    createWaybill: 'Kọ Risiti Ẹrù Tuntun',
    registerBus: 'Kọ Rụkọ Ọkọ̀',
    outgoingBuses: 'Àwọn Ọkọ̀ Tí Ń Kúrò',
    incomingBuses: 'Àwọn Ọkọ̀ Tí Ń Bọ̀',
    waybillHistory: 'Ìtàn Gbogbo Ẹrù',
    dashboard: 'Dashbọọdu',
    analytics: 'Agbára Owó',
    settings: 'Àwọn Ntọala',
    myWaybillsReceipts: 'Àwọn Risiti & Ẹrù Mi',
    activeWaybills: 'Àwọn Ẹrù Tí Ń Lọ',
    deliveredWaybills: 'Àwọn Ẹrù Tí Ó Ti Dé',
    totalSpent: 'Gbògbò Owó Tí A Na',
    searchPlaceholder: 'Tọpa nipasẹ koodu waybill, ẹrù, tàbí orukọ...',
    noWaybillsFound: 'Kò sí ẹrù tí a rí fún àwárí yìí.',
    copyPin: 'Kọọpù Pickup PIN',
    pinCopied: 'A Ti Kọọpù Pickup PIN!',
    pickupInstruction: 'Gosi koodu PIN 6 yìí fún àwọn oníṣẹ́ garaji nígbà tí o fẹ́ gbà ẹrù rẹ',
    customerDashboardTitle: 'Ibì Ndí Oníbàárà',
    welcomeUser: 'Káàbọ̀ padà,',
    customerDesc: 'Tọpa àwọn ẹrù rẹ, risiti rẹ àti koodu Pickup PIN rẹ',
    staffPortalTitle: 'Ibì Ndí Oníṣẹ́ Park',
    managerPortalTitle: 'Ibì Ndí Mánéjà',
    companyPortalTitle: 'Ibì Ndí Kháńpánì',
    adminPortalTitle: 'Ibì Ndí Admin',
    overview: 'Àkópọ̀',
    myBranches: 'Àwọn Garaji Ọkọ̀',
    staffMembers: 'Àwọn Oníṣẹ́',
    vehiclesAndBuses: 'Àwọn Ọkọ̀',
    revenueLogs: 'Àkọọ́lẹ̀ Owó',
    systemStats: 'Ìṣirò Ètò',
    markDeparted: 'Ami Ọkọ̀ Bíi Ó Ti Kúrò',
    markArrived: 'Ami Ọkọ̀ Bíi Ó Ti Dé',
    senderInfo: '1. Ìsọfúnni Nípa Oníranṣẹ́',
    senderNameLabel: 'Orukọ Kikun Oníranṣẹ́',
    senderPhoneLabel: 'Nọmba Agogo Oníranṣẹ́',
    receiverInfo: '2. Ìsọfúnni Nípa Onígbà',
    receiverNameLabel: 'Orukọ Kikun Onígbà',
    receiverPhoneLabel: 'Nọmba Agogo Onígbà',
    packageInfo: '3. Àkọsílẹ̀ Ẹrù & Owó',
    itemDescLabel: 'Àpèjúwe Ẹrù Àti Ìwọ̀n Rẹ̀',
    waybillFeeLabel: 'Owó Risiti Ẹrù (₦)',
    destinationParkLabel: '4. Garaji Tí Ọkọ̀ Ń Lọ',
    selectParkOption: '-- Zaɓi Garaji Tí Ó Ń Lọ --',
    selectBusLabel: '5. Zaɓi Ọkọ̀ Tí Ń Gbé Ẹrù',
    selectBusOption: '-- Zaɓi Ọkọ̀ --',
    noBusesWarning: 'Kò sí ọkọ̀ tí ó ń lọ síbẹ̀ níbáyìí. Kọ rụkọ ọkọ̀ kọ́kọ́!',
    submitWaybill: 'Buga Àti Pamo Risiti',
    plateNumber: 'Nọmba Plate Ọkọ̀',
    driverName: 'Orukọ Direba',
    driverPhone: 'Nọmba Agogo Direba',
    totalRevenue: 'Gbogbo Owó Tí A Gba',
    todayWaybills: 'Àwọn Ẹrù Ti Ọjọ́ Òní',
    activeBusesCount: 'Àwọn Ọkọ̀ Tí Ń Gbé Ẹrù',
    details: 'Ìsọfúnni Kikun',
    shareWhatsApp: 'Aika lori WhatsApp',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguage: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('waybilla_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    if (language && language !== 'en') {
      try {
        const domain = window.location.hostname;
        document.cookie = `googtrans=/en/${language}; path=/; domain=${domain}`;
        document.cookie = `googtrans=/en/${language}; path=/`;
      } catch (e) {
        console.log('Language cookie restore:', e);
      }
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('waybilla_lang', lang);

    // Synchronize 100% auto-translation across the DOM
    try {
      const gtCombo = document.querySelector('.goog-te-combo') as HTMLSelectElement | null;
      if (gtCombo) {
        gtCombo.value = lang === 'pcm' ? 'pcm' : lang;
        gtCombo.dispatchEvent(new Event('change'));
      }
      // Set google translate cookie for persistent 100% full-page translation
      const domain = window.location.hostname;
      const targetLang = lang === 'en' ? 'en' : lang;
      document.cookie = `googtrans=/en/${targetLang}; path=/; domain=${domain}`;
      document.cookie = `googtrans=/en/${targetLang}; path=/`;
    } catch (e) {
      console.log('Language sync initialized:', e);
    }
  };

  const currentLanguage = LANGUAGES.find((l) => l.code === language) || LANGUAGES[0];

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
